[build]
  publish = "dist"
  command = "npm run build"

# Redirect for privacy page with trailing slash
[[redirects]]
  from = "/privacy/"
  to = "/index.html"
  status = 200
  force = true

# Redirect for privacy page without trailing slash
[[redirects]]
  from = "/privacy"
  to = "/index.html"
  status = 200
  force = true

# Redirect for terms page with trailing slash
[[redirects]]
  from = "/terms/"
  to = "/index.html"
  status = 200
  force = true

# Redirect for terms page without trailing slash
[[redirects]]
  from = "/terms"
  to = "/index.html"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "20"