import React from 'react';
import { Button } from './Button';
import { useTranslation } from 'react-i18next';

interface TermsOfServiceProps {
  onBack: () => void;
}

export function TermsOfService({ onBack }: TermsOfServiceProps) {
  const { i18n } = useTranslation();
  const isGerman = i18n.language === 'de';

  // Full Terms of Use text (English version) with enhanced Tailwind styling
  const termsEnglish = (
    <>
      <h2 className="text-2xl font-bold mt-8 mb-4">1. Introduction</h2>
      <p className="mb-2 text-sm">
        Welcome to UNITAIN (“we,” “us,” or “our”), operated by UNITAIN LLC, a limited liability company organized under the laws of the State of Wyoming, with its principal place of business at 5830 E 2nd St, Ste 7000 #22789, Casper, Wyoming 82609, USA (hereinafter “UNITAIN” or “Company”).
      </p>
      <p className="mb-2 text-sm">
        These Terms of Use (“Terms”) govern your access to and use of the UNITAIN platform, websites, mobile applications, and any related services (collectively, the “Platform”). By creating an account or otherwise using the Platform, you agree to be bound by these Terms and by our Privacy Policy (the “Privacy Policy”).
      </p>
      <p className="mb-2 text-sm">
        If you do not agree to these Terms, you must not use our Platform.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">2. Beta Phase Notice</h2>
      <p className="mb-2 text-sm">
        Some or all parts of the Platform may be labeled “Beta,” “Preview,” or “Early Access” (collectively, “Beta Services”). Beta Services are provided “as is” and may contain defects or errors. We do not guarantee the full functionality or continuous availability of Beta Services and may discontinue them without notice.
      </p>
      <p className="mb-2 text-sm">
        By using Beta Services, you acknowledge and agree that data loss, service interruptions, or other issues may occur. No legal claims or liability shall be asserted against UNITAIN for such Beta Services beyond the extent permitted by law.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">3. Services Provided</h2>
      <p className="mb-2 text-sm">
        UNITAIN offers AI-powered data extraction and organizational tools for administrative and bureaucratic documents. This may include, but is not limited to:
      </p>
      <ul className="list-disc ml-8 mb-4">
        <li className='text-sm'>Optical Character Recognition (OCR) for scanned documents.</li>
        <li className='text-sm'>Machine learning- or AI-based analysis to highlight missing documentation or potential discrepancies.</li>
        <li className='text-sm'>General guidance on vehicle import processes in certain jurisdictions (e.g., Portugal).</li>
      </ul>
      <p className="mb-2 text-sm">
        <span className="font-bold">No Legal or Tax Advice:</span> The content, recommendations, or outputs generated by our Platform (including any AI tools or expert systems) are for general informational purposes only. We do not provide legal, financial, or tax advice. You remain solely responsible for verifying any results, data, or recommendations with qualified professionals or official government sources.
      </p>
      <p className="mb-2 text-sm">
        <span className="font-bold">User Responsibility with Authorities:</span> You are solely responsible for meeting any deadlines, filing any official paperwork, and bearing any fees owed to government entities or third parties (e.g., customs, tax authorities). UNITAIN does not guarantee any specific outcome (such as a tax exemption, refund, or successful vehicle import).
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">4. User Accounts</h2>
      <p className="mb-2 text-sm">
        <span className="font-bold">Account Creation:</span> To access certain features, you must create a user account. You agree to provide accurate and complete information during registration and to keep this information up to date.
      </p>
      <p className="mb-2 text-sm">
        <span className="font-bold">Account Security:</span> You are responsible for maintaining the confidentiality of your login credentials. You must notify us immediately if you suspect any unauthorized access to your account.
      </p>
      <p className="mb-2 text-sm">
        <span className="font-bold">Eligibility:</span> You must be at least 18 years old or the age of majority in your jurisdiction to use this Platform. By creating an account, you represent that you meet this requirement.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">5. Payment and Refunds</h2>
      <p className="mb-2 text-sm">
        <span className="font-bold">Freemium vs. Premium Services:</span> Some automated features may be available free of charge (the “Freemium Services”). Other Premium Services—especially those involving manual processing, expert review, or official submissions—may require payment of fees.
      </p>
      <p className="mb-2 text-sm">
        <span className="font-bold">Pricing and Billing:</span> If you opt for any paid services, you will be informed of the applicable fees before purchase. By confirming the purchase, you agree to pay the stated fees in accordance with the payment terms provided at checkout.
      </p>
      <p className="mb-2 text-sm">
        <span className="font-bold">Refund Policy:</span> Refunds may be offered under certain conditions, which will be outlined separately or displayed during purchase. No refunds are generally provided once a manual review or official submission has been initiated, except as required by law.
      </p>
      <p className="mb-2 text-sm">
        <span className="font-bold">Consumer Rights (EU):</span> If you are an EU consumer, you may have a statutory “cooling-off” or withdrawal right under certain circumstances. Details will be provided to you where applicable. However, once digital services (especially personalized or immediately consumable) have started with your consent, you may lose your right of withdrawal.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">6. Consumer Rights (EU) and Governing Law</h2>
      <p className="mb-2 text-sm">
        <span className="font-bold">Governing Law:</span> These Terms shall be governed by and construed in accordance with the laws of the State of Wyoming, USA, without regard to its conflict of laws principles.
      </p>
      <p className="mb-2 text-sm">
        <span className="font-bold">EU Consumer Protection:</span> Nothing in these Terms shall deprive EU consumers of the protection granted by mandatory provisions of the law in the country of their habitual residence. If you are a consumer residing in the European Union, you may bring claims in the courts of your home country in accordance with applicable consumer protection laws.
      </p>
      <p className="mb-2 text-sm">
        <span className="font-bold">Jurisdiction:</span> For users not qualifying as EU consumers, any dispute arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the competent courts in the State of Wyoming, USA.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">7. Hosting, Data Storage & Transfers</h2>
      <p className="mb-2 text-sm">
        <span className="font-bold">Data Hosting in the EU:</span> UNITAIN hosts and processes user data primarily on servers located in the European Union (“EU”). This is intended to comply with EU data protection standards under the General Data Protection Regulation (“GDPR”).
      </p>
      <p className="mb-2 text-sm">
        <span className="font-bold">Transfers to the USA:</span> As UNITAIN is a US-based entity, certain personal data may be transferred to the USA for business, administrative, or support purposes. Where required by law (e.g., for EU data subjects), we rely on Standard Contractual Clauses (SCCs) or other recognized transfer mechanisms to ensure an adequate level of data protection.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">8. Intellectual Property</h2>
      <p className="mb-2 text-sm">
        <span className="font-bold">Platform Ownership:</span> All rights, title, and interest in and to the Platform (including software, designs, AI models, text, graphics, and logos) belong to UNITAIN or its licensors. These Terms do not grant you any right to use UNITAIN’s trademarks, logos, or copyrighted materials except as necessary to access and use the Platform.
      </p>
      <p className="mb-2 text-sm">
        <span className="font-bold">User Content:</span> By uploading or submitting any documents or information to the Platform (“User Content”), you grant UNITAIN a non-exclusive, worldwide, royalty-free license to store, process, and display such content for the purpose of providing our services.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">9. Disclaimers and Limitations of Liability</h2>
      <p className="mb-2 text-sm">
        <span className="font-bold">Disclaimer of Warranties:</span> To the fullest extent permitted by law, the Platform is provided “as is” and “as available” without warranties of any kind, whether express or implied. We do not warrant that (i) the Platform will be error-free, (ii) any AI-generated result or OCR output will be accurate or reliable, or (iii) any official entity will accept your documentation or grant any exemption, tax refund, or other benefit.
      </p>
      <p className="mb-2 text-sm">
        <span className="font-bold">No Legal or Tax Advice:</span> UNITAIN is not a law firm, tax advisor, or other regulated professional advisor. Any information or output provided by the Platform is of a general and informational nature. You should seek professional advice for any complex or high-stakes questions.
      </p>
      <p className="mb-2 text-sm">
        <span className="font-bold">Limitation of Liability:</span> To the maximum extent permitted by applicable law, UNITAIN shall not be liable for any indirect, consequential, exemplary, incidental, or special damages, including but not limited to lost profits, loss of data, or interruption of business. For EU consumers, we do not limit liability where it cannot be lawfully excluded (e.g., for intentional misconduct, gross negligence, or personal injury).
      </p>
      <p className="mb-2 text-sm">
        <span className="font-bold">User Responsibilities:</span> You acknowledge that you remain solely responsible for meeting deadlines, submitting documentation to authorities, and verifying that any official processes have been completed successfully. We do not guarantee any particular outcome.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">10. Termination</h2>
      <p className="mb-2 text-sm">
        <span className="font-bold">Termination by Us:</span> We reserve the right to suspend or terminate your access to the Platform at any time and for any reason, including breach of these Terms.
      </p>
      <p className="mb-2 text-sm">
        <span className="font-bold">Termination by You:</span> You may cease using the Platform at any time. Termination does not relieve you of any payment obligations incurred prior to termination.
      </p>
      <p className="mb-2 text-sm">
        <span className="font-bold">Survival:</span> Any provisions of these Terms that, by their nature, should survive termination (e.g., disclaimers of warranties, limitation of liability, governing law) shall remain in effect.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">11. Changes to These Terms</h2>
      <p className="mb-2 text-sm">
        We may modify these Terms from time to time. If we make any material changes, we will provide notice (e.g., by email or prominently posting on the Platform). By continuing to use the Platform after such changes become effective, you agree to be bound by the updated Terms.
      </p>

      <h2 className="text-2xl font-bold mt-8 mb-4">12. Contact Us</h2>
      <p className="mb-2 text-sm">
        If you have any questions about these Terms or need assistance, please contact us at:
      </p>
      <p className="mb-2 text-sm">
        UNITAIN LLC<br />
        5830 E 2nd St, Ste 7000 #22789<br />
        Casper, Wyoming 82609, USA<br />
        Email: <a href="mailto:info@unitain.net" className="text-primary-600 hover:underline">info@unitain.net</a>
      </p>
    </>
  );

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div className="max-w-5xl mx-auto bg-white shadow-lg rounded-lg p-5 overflow-hidden">
         <div className="border-b border-gray-200 flex justify-between">
              <h1 className="text-3xl font-bold text-gray-900">   {isGerman ? 'Nutzungsbedingungen' : 'Terms of Use'}</h1>
            <Button variant="outline" onClick={onBack} className="mb-4">{isGerman ? 'Zurück' : 'Back'}</Button>
          </div>

      <div className="prose prose-lg max-w-none ">
        {isGerman ? (
          <>
            <p className="mb-6">
              Hinweis: Die folgenden Nutzungsbedingungen werden in englischer Sprache angezeigt. Bitte beachten Sie, dass dies die offizielle Version ist.
            </p>
            {termsEnglish}
          </>
        ) : (
          termsEnglish
        )}
      </div>
    </div>
    </div>
  );
}

export default TermsOfService;
